[[popuset_shim]]
arch = "armv7l"
git-tree-sha1 = "f13277c5c4240a9053dbfd7f2d8413d4763f5ece"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "051a1589c408095ec7684a821b7bce5a5e3da698061c1eef8ab5d0fa5991810a"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "d81f42fee5d4dde316abd28d1777316b374c5934"
os = "macos"

    [[popuset_shim.download]]
    sha256 = "eab28f2294c5a72e24c78c4c3de82cae78c56956f717f2501b3622ad1ccc3e24"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-apple-darwin14.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "31fcc4ba67150e39300e0ab4c282676377cb059a"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "1b851fd307f9bb9c9f366331557be8f2d687f9b8b9ba824fa4582f19fce10dda"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-linux-gnu.tar.gz"
