[[popuset_shim]]
arch = "armv7l"
git-tree-sha1 = "48e0392c36ef769d55e84e4d553aedffb2c42db2"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "1852053603ce26dabfd086cb5e1e05e0f7beb97abc53e2d3f2be5d5a956fbea6"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "b8dc86384ca778e9677be3bdc49fffecfcf5341a"
os = "macos"

    [[popuset_shim.download]]
    sha256 = "c208019c48444cc21a4bcf9be48b955e3e93a1764ecc466d1089b07ba1d9cf0e"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-apple-darwin14.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "f0d897f5cc9e7c836bef72e9c5a10b1bb07b7504"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "867bb24595e2da07fd79ec3642a87e29201f838f2a96ba6c032e6196fff9ee50"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-linux-gnu.tar.gz"
