[[popuset_shim]]
arch = "armv7l"
git-tree-sha1 = "9f8a07b6b11086e420fc6706364f6c4ab0332465"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "94384a70fb5cd3dc5ebe07099f9b15952e7d839f51273cc082d91395d99d90b1"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "3a352f4a59560b4074d3af5f97ec47f78b1b3965"
os = "macos"

    [[popuset_shim.download]]
    sha256 = "352f8ca4375c3516e96fe18f6fef6da664751b6b6729c9a579cb65b3b5feb523"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-apple-darwin14.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "52a7cfa32e29e7c7f9533b64be42c2fea80e4544"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "369af26fa40da3fb0c9b3732e65a7b56735a89d0354b0493e38e00b8fe8e077c"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-linux-gnu.tar.gz"
