[[popuset_shim]]
arch = "armv7l"
git-tree-sha1 = "9f8a07b6b11086e420fc6706364f6c4ab0332465"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "7c33f41617fe709a3e32fc78e34f38f57cd2f2200bd53ac9abfecc3a73e4a8ab"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "3a352f4a59560b4074d3af5f97ec47f78b1b3965"
os = "macos"

    [[popuset_shim.download]]
    sha256 = "4a7217d3e82314041b359602d5fd9fa7ac6a7bed60557b89ee61d0112db716ef"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-apple-darwin14.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "b9998b4d56f73cc8965ae818e5f875189b28eecd"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "082a0fc9ca13cb111aacb7e9d36333fe0e4f6d7555f86d6dd901def1e895d2ce"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-linux-gnu.tar.gz"
