[[popuset_shim]]
arch = "armv7l"
git-tree-sha1 = "c27dc3bf052cfe141d44c26a4e33aabb877078ce"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "15b6adcd8efbe6f3fbd8126d250251cb96234b088ebab39dd1d747a80fdb95d2"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "a0d85917db0bc04e629674282b525fab274323a2"
os = "macos"

    [[popuset_shim.download]]
    sha256 = "61e3117cdd2ebe6b5f1f49f053111bbb43c55e13b7616ecb952c9e6184c9ce54"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-apple-darwin14.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "368887b147e0ce350c4fd0e2bcabf7d3b008167a"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "642604bd11eb9a9a9f7d28fbe35b84b0790a29bf66b01aca93f29890361e5977"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-linux-gnu.tar.gz"
