[[popuset_shim]]
arch = "armv7l"
git-tree-sha1 = "de04aa66a1cc39fe0221bbce1249adbf042f0a9f"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "a03b858953e3b224386ac23ac76792688b09e9ffd14651839e2d6e70752c4bed"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "5b279e1a6acf56820d9766b8b44fc5d6e8241b54"
os = "macos"

    [[popuset_shim.download]]
    sha256 = "6554fe9697a24fdc169def90bd40816a635ee019154846fe6cca1edf4ab0ed20"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-apple-darwin14.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "c1f55ec5920f02fa1c7a49d294f5e90b7431ec62"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "bac86ebd6d3568e65c3a54752a1c8e278b55e53b618e284a86064d7b28089e30"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-linux-gnu.tar.gz"
