[[popuset_shim]]
arch = "armv7l"
git-tree-sha1 = "15d61c1e40348d6dcb349dbb11588a23368fa9f0"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "a58a526fb510cb31995f8f19182ad0a0fda11b3200fdc79b2ae426de4311296b"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.armv7l-linux-gnueabihf.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "2f365aa2c3cd6ca928c3b0d3d7092397eb0f0cb4"
os = "macos"

    [[popuset_shim.download]]
    sha256 = "e7d55605587c447e09a49930c0df3387115eda02cc2988c3f3cd1148cd6c2967"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-apple-darwin14.tar.gz"
[[popuset_shim]]
arch = "x86_64"
git-tree-sha1 = "56c05a0d3494cb920c10253b497d559b9eb03f37"
libc = "glibc"
os = "linux"

    [[popuset_shim.download]]
    sha256 = "27767dec149f3515a307fa80931bcddc09b6819ea9a53041a465f30dd8d18c63"
    url = "https://github.com/staticfloat/popuset_shim_jll.jl/releases/download/popuset_shim-v0.0.1+0/popuset_shim.v0.0.1.x86_64-linux-gnu.tar.gz"
